name: Sribuu_Smart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # =======================================================
  # âœ… WAJIB ADA: Localization
  # =======================================================
  flutter_localizations:
    sdk: flutter
  # =======================================================

  google_sign_in: ^6.1.0

  # UI dan Icon
  cupertino_icons: ^1.0.6

  # Widget progress dan chart
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0

  # =======================================================
  # âœ… PERBAIKAN VERSI INTL (Sesuai Error Log Anda)
  # =======================================================
  intl: ^0.20.2 
  # =======================================================
  
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # ðŸ”¥ FIREBASE
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1

  # PDF
  pdf: ^3.7.3
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter tools
  flutter_lints: ^4.0.0

  # Generator Ikon
  flutter_launcher_icons: ^0.13.1

# ----------------------------------------------------
# ðŸ› ï¸ KONFIGURASI TOOLS TAMBAHAN
# ----------------------------------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Sribuu Smart.png" 

flutter:
  uses-material-design: true

  # Folder Assets
  assets:
    - assets/